datasources:
  principal:
    #    jdbcUrl: jdbc:postgresql://ec2-34-235-108-68.compute-1.amazonaws.com:5432/d1uif04t1n3ae8?ssl=true&amp;sslfactory=org.postgresql.ssl.NonValidatingFactory
    jdbcUrl: jdbc:postgresql://192.168.159.130:5432/postgres?ssl=true&amp;sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require
    username: postgres
    password: postgres
    maximumPoolSize: 1
  test:
    jdbcUrl: jdbc:h2:file:./target/db/testdb;MODE=PostgreSQL
    username: sa
    password:
    maximumPoolSize: 1
    # Spring properties
    spring:
      data:
        mongodb:
          host: localhost
          port: 27017
          uri: postgres://localhost/test
      application:
        name: user-service  # Service registers under this name

    endpoints:
      health:
        enabled: yes
      shutdown:
        enabled: yes

    management:
      context-path: /admin
    logging:
      level:
        org:
          springframework:
            web:
              client: DEBUG

    # HTTP Server
    server:
      port: 8080   # HTTP (Tomcat) port